# (tag, question, really_asking, explanation_for_us, say, dont)
FAQ = [
("SEO","What exactly will you do for SEO this month?",
 "Is this real work or just a buzzword on the invoice?",
 "List the concrete tasks: review, titles/descriptions, headings, keywords, internal links, content fixes, Search Console, monitoring.",
 "We'll review your site, fix page titles and descriptions, tidy up headings, add the right travel keywords naturally, link related pages together, improve weak content, and set up Google Search Console so we can see how you appear on Google. You'll get a list of what we changed.",
 "Rankings, traffic numbers, or a page-1 date."),
("SEO","When will my website rank on Google?",
 "When will I see a return on this?",
 "Nobody controls Google's timing. Month 1 fixes the foundation; movement in impressions usually shows over weeks to months.",
 "I can't give you an honest date — Google decides that, and it depends on competition too. What I can tell you is that we'll fix the basics this month and show you your real Search Console numbers so you can see the trend as it develops.",
 "“Page 1 in 30/60/90 days.”"),
("SEO","Which keywords will you target?",
 "Will you target things that actually bring my customers?",
 "Pick realistic keywords tied to what they sell and where. Long, specific phrases (e.g. 'Kerala honeymoon package from Delhi') are easier than broad ones ('travel agency').",
 "We'll focus on specific phrases linked to your actual packages and destinations — the kind of thing a real customer types before they enquire. Broad terms like 'travel agency' are dominated by big portals, so we'll be practical.",
 "Ranking for broad terms like “travel agency India”."),
("SEO","Why can't we just rank for 'best travel agency'?",
 "Why not aim for the big one?",
 "Broad, high-competition terms are dominated by large brands; also 'best' searches are often answered by listicles and review sites.",
 "Those broad terms are dominated by very large travel companies with years of history. We'll get far better value going after specific searches where you actually have a chance and where the person is closer to booking.",
 "That we can compete with MakeMyTrip-scale sites in Month 1."),
("SEO","What is Google Search Console and why do we need it?",
 "Is this another tool I'll have to pay for?",
 "Free Google tool. Shows searches, clicks, indexing issues. Client owns it; we're added as users.",
 "It's a free tool from Google that shows how your website appears in Google — what people searched, how often you showed up, and any problems Google found. It will be under your own Google account; we'll just have access to it.",
 "That it will improve rankings by itself — it only measures."),
("GEO","What is GEO? Will my business show up in ChatGPT?",
 "Can you get AI to recommend me?",
 "GEO = clear, structured, consistent information for AI tools. No one controls what AI tools say.",
 "GEO means making your website's information clear and well-organised so AI tools like ChatGPT or Google's AI answers can understand your business correctly. We can't control whether they mention you — nobody can — but we can make sure they have clear information to work with.",
 "“You'll appear in ChatGPT/Gemini/Perplexity.”"),
("GEO","How will you measure GEO?",
 "How will I know it's working?",
 "Honestly: there's no reliable tracking tool yet. We can do manual spot-checks and track related SEO signals.",
 "Honestly, this is still a new area and there's no reliable report for it yet. We'll track the related Google data in Search Console and do occasional manual checks, and we'll be upfront about what can and can't be measured.",
 "An 'AI visibility score' or made-up tracking."),
("AEO","What is AEO and how is it different from SEO?",
 "Am I paying twice for the same thing?",
 "AEO = question-and-answer content. It overlaps with SEO — same pages, different angle. We don't charge separately; it's all within the ₹20,000.",
 "SEO makes your pages findable on Google. AEO focuses on answering the specific questions your customers ask — like 'best time to visit Bali' or 'can I customise my package'. They overlap, and it's all part of the same monthly work.",
 "That AEO is a separate product with its own guaranteed results."),
("AEO","Will my FAQs show up in Google's answer box?",
 "Is there a guaranteed visible outcome?",
 "Google picks featured snippets/AI answers. Clear answers improve chances only.",
 "They might, but Google decides what goes in those boxes and it changes often. Clear, direct answers improve the chance, and they also help real visitors decide to enquire — which is the main point.",
 "Featured snippets or AI answer placement."),
("Meta Ads","How many leads will I get from ₹10,000?",
 "Is this money going to pay off?",
 "Unknowable in advance. Month 1 is a test to find the real cost per lead.",
 "I can't honestly give you a number before we run it. The point of this ₹10,000 is to find out what a lead actually costs for your business, which ad works best, and whether the leads are genuine. That tells us whether spending more makes sense.",
 "Any lead number or cost-per-lead estimate."),
("Meta Ads","Is the ₹10,000 part of your ₹20,000?",
 "What's my total cost?",
 "No. ₹10,000 goes from client's card directly to Meta. Our fee is separate. Total ₹30,000. Meta may add GST on ad spend.",
 "No — the ₹10,000 is paid directly by you to Meta through your own ad account, so you can see every rupee spent. Our ₹20,000 is our service fee. So the total for the month is ₹30,000. Meta may add tax on top of the ad spend, which you'll see on your billing page.",
 "That we'll 'manage' or hold the ad money."),
("Meta Ads","Why 5 creatives but only 3 running?",
 "Am I paying for work that gets wasted?",
 "Testing 5 lets us find the best 3 instead of guessing; small budget is better concentrated on winners.",
 "We start all 5 so we can see which ones actually work for your audience, instead of guessing. Then we put the budget behind the best 3. With a ₹10,000 budget, spreading money across weaker ads would waste it.",
 "That all 5 will run all month."),
("Meta Ads","Who will you target?",
 "Are you going to show my ads to the right people?",
 "Location + age + interests, based on client's real customer profile. Keep it focused.",
 "We'll build the audience around who your customers actually are — the cities they're from, age range, and travel interests. That's why we'll ask you about your typical customers. We'll keep it focused because the budget is a test budget.",
 "“We'll only show ads to people ready to book.”"),
("Meta Ads","Will leads come to my phone/WhatsApp?",
 "How do I receive leads?",
 "Website form leads → admin area + email notification. Instant-form leads → Meta Leads Center (client downloads). Decide form type before launch.",
 "Website enquiries go into your private admin area, and you'll get a notification. If we use Meta's own lead form, those leads sit in your Meta account and we'll show you exactly where to find them. Either way, please check them daily and reply quickly.",
 "Automatic WhatsApp delivery or CRM integration (not in scope)."),
("Meta Ads","Can you run ads on Google too?",
 "Can you do more?",
 "Google Ads is not in the Month 1 scope.",
 "Google Ads isn't part of this month's plan. Once we have results from Meta, we can discuss whether Google Ads makes sense and scope it separately.",
 "To “just set up a quick Google campaign”."),
("Instagram","Will daily posting increase my followers?",
 "Will people see me growing?",
 "Consistency helps, but growth is gradual and not guaranteed. Profile visits/DMs matter more.",
 "Posting regularly usually helps, but follower growth is gradual and depends on many things we don't control. We'll focus on content people save, share and message you about — those matter more for business than follower count.",
 "Follower numbers or viral reels."),
("Instagram","Who will create the posts and reels? Do you need my photos?",
 "How much work is this for me?",
 "We create; client supplies real photos/videos and info. Licensed stock can fill gaps. Real footage performs and builds trust better.",
 "We'll plan, design and write everything. Your real trip photos and videos make the content much more believable, so please share whatever you have. Where there are gaps, we'll use properly licensed stock images.",
 "That we'll shoot on-location video or travel for content."),
("Instagram","Will you reply to comments and DMs?",
 "Is community management included?",
 "Not explicitly in scope. Travel DMs are sales conversations — client should handle them. We can flag comments we see.",
 "Enquiries in DMs are really sales conversations, so it's best your team replies — you know the prices and availability. If we see comments or questions while posting, we'll flag them to you.",
 "Full-time DM/comment management."),
("Instagram","Can I approve posts before they go live?",
 "Do I have control?",
 "Yes — content calendar approval. But approvals must be timely.",
 "Yes. We'll share the content plan in advance for your approval. The only request is quick feedback — ideally within a day or two — so we can keep posting daily.",
 "Unlimited revisions."),
("Website","Will you redesign my website?",
 "What am I getting on the website?",
 "No. Fixes, legal pages, Search Console, admin lead area. Redesign is separate.",
 "Not a full redesign — this month is about fixing what affects user experience and enquiries, adding legal pages, connecting Search Console, and setting up your lead area. If you want a redesign later, we can quote it separately.",
 "A redesign, new features, or unlimited changes."),
("Website","Why do I need legal pages?",
 "Is this just filler work?",
 "Trust, Meta lead form requirement (privacy policy), payment gateways, data protection.",
 "Customers are trusting you with personal details and significant payments, so clear privacy, terms and refund policies build confidence. Meta also requires a privacy policy for lead forms. We'll draft them based on your actual policies, and you should review them — ideally with your legal adviser.",
 "That our drafts are legal advice."),
("Website","Who can see my leads?",
 "Is my customer data safe and mine?",
 "Only the client — they set the password. We don't keep it.",
 "Only you. You'll set the admin password yourself, and we won't know it. The leads come to your system, not to us.",
 "That the system is 'hack-proof'."),
("Leads","Will every enquiry become a booking?",
 "Is this going to make me money?",
 "No. Conversion depends on the client's pricing, speed and follow-up.",
 "No — some people will just be exploring prices or dates. How many turn into bookings depends a lot on how fast your team responds and the quote itself. Quick replies make a big difference.",
 "Any conversion rate or sales figure."),
("Leads","Some leads are junk. Why?",
 "Are you sending me rubbish?",
 "Normal to some extent, especially with instant forms. Client feedback helps us tighten targeting/form.",
 "Some low-quality leads are normal with any online advertising. If you tell us which ones were not genuine, we can add a qualifying question to the form or adjust the audience to improve quality.",
 "Zero junk leads."),
("Reporting","How will I know what you did?",
 "Accountability.",
 "Mid-month update + month-end report with work done, numbers, learnings, recommendation.",
 "You'll get a short update mid-month and a full report at the end — what we did, the real numbers from Google, Instagram and Meta, what worked, what didn't, and what we recommend next.",
 "Daily reports (unless agreed)."),
("Reporting","Can I see the ad account myself?",
 "Transparency.",
 "Yes — it's their account; they pay Meta directly.",
 "Absolutely — it's your ad account. You can log in anytime and see spend and results. We'll show you where to look.",
 "—"),
("Pricing","Why ₹20,000 — what does it cover?",
 "Is this worth it?",
 "Six workstreams of labour; ad spend separate. Be clear, not defensive.",
 "It covers six pieces of work: SEO, GEO and AEO content work, 30 posts and 10 reels, creating and managing 5 ads, website fixes and legal pages, and building your private lead area — plus reporting. The ad budget is separate and goes straight to Meta.",
 "“Guaranteed ROI.”"),
("Timelines","When will everything be set up?",
 "When does work start showing?",
 "Weeks 1–2 setup/build, weeks 3–4 ads live and optimising. Depends on access.",
 "The first two weeks are mostly setup and fixes, ads go live around week three, and the last week is optimising and reporting. Instagram starts as soon as the content plan is approved. The biggest factor is how quickly we get access and material from you.",
 "Fixed go-live dates before access is received."),
("Client role","What do you need from me?",
 "How involved do I need to be?",
 "Access, info, assets, approvals, lead follow-up.",
 "Mainly: access to your website and Meta/Instagram accounts, details of your packages and prices, any photos or videos, quick approvals, and fast replies to the enquiries that come in. We'll send one simple checklist.",
 "That the client doesn't need to do anything."),
("Future","What happens after Month 1?",
 "Am I locked in?",
 "No lock-in. Month-end review → continue/adjust/stop based on data.",
 "At the end of the month we'll go through the results together. If the data shows something working, we'll recommend what to continue or scale. If not, we'll be honest about that. There's no obligation to continue.",
 "Month 2 results in advance, or discounts we haven't agreed."),
]

# (question, say, note_for_us)
HARD = [
("“Why should I pay ₹20,000?”",
 "That's a fair question. The ₹20,000 covers six areas of work this month — website SEO, AI and answer-focused content, 30 posts and 10 reels, 5 ad creatives with a month of ad management, website fixes with legal pages, and your own private lead system — plus reporting. You'll get a clear list of everything completed, so you can judge the value yourself.",
 "Walk through deliverables, not promises. Don't apologise for the price."),
("“Others are doing this for ₹15,000.”",
 "That may well be true, and prices vary. I'd suggest comparing exactly what's included — number of posts and reels, whether ads, website fixes, legal pages and a lead system are part of it, and how reporting works. Our price is for this specific scope. If the scope needs to change to fit a budget, we can talk about that openly.",
 "Never criticise competitors. If reducing price, reduce scope too."),
("“Can you guarantee leads?”",
 "No, and I'd be careful of anyone who does. Meta decides who sees ads and customers decide whether to enquire. What we guarantee is the work — properly made ads, a structured test, active monitoring and honest reporting on what the ₹10,000 produced.",
 "Stay calm and consistent. This answer should never change."),
("“Can you guarantee Google ranking?”",
 "No one can guarantee Google rankings — Google controls that, and even Google itself says so. We can guarantee we'll fix the site's foundations properly and show you the real Search Console data as it develops.",
 "Google's own guidance warns against anyone guaranteeing rankings — a useful, neutral point."),
("“When will I get results?”",
 "It depends on the channel. Ads give data fastest — within days of launching. Instagram builds gradually. SEO usually takes the longest, often months. This month is about getting the foundation right and learning from the ad test, so by month-end we'll have real data to decide on next steps.",
 "Separate channels; don't give one blanket date."),
("“Why didn't I get any leads?”",
 "I understand that's frustrating. Let's look at where it stopped — views, clicks, or the form. Here's what the numbers show, and here's what we're changing. A test that doesn't produce leads still tells us something important, so the next spend is better directed.",
 "Come with the data and a specific next action. Never blame the client in the moment — check lead response and offer calmly afterwards."),
("“Why should I spend ₹10,000 on ads?”",
 "SEO and Instagram take time to build. Ads are the fastest way to find out whether people respond to your packages and what an enquiry actually costs. ₹10,000 is a controlled amount to learn that before any bigger decision — and it goes directly to Meta from your account.",
 "If they don't want to spend it, don't pressure. Note the ads part of scope can't be delivered without budget."),
("“Can you get me 100 leads?”",
 "I can't promise a number, because it depends on the offer, audience and competition. After this test we'll know your real cost per lead. Then we can calculate honestly what budget would be needed to aim for more — and whether that makes business sense for you.",
 "Don't do the maths live with guessed numbers."),
("“Why are there clicks but no enquiries?”",
 "That's actually useful information — it means the ad is interesting but something after the click is stopping people. Usually it's the form, page speed on mobile, an unclear price or offer, or people just browsing. We'll check each and fix what's in our control.",
 "Check: form works? Mobile speed? Offer clear? Right audience?"),
("“What if I don't get results in the first month?”",
 "Then we'll tell you clearly, show you why, and recommend what to change — or whether to stop. Month 1 is meant to build the foundation and test, so even a weak result gives us data. You're not locked in beyond this month.",
 "Honesty here builds long-term trust."),
("“Why do you need access to my accounts?”",
 "We need it to do the work — edit the website, set up Search Console, publish on Instagram, and run ads. Wherever possible we'll use partner access instead of your passwords, so you stay the owner and can remove us anytime. Your lead admin password stays only with you.",
 "Use Meta Business partner access and Google user access, not shared passwords."),
("“Why isn't SEO giving immediate traffic?”",
 "Google needs time to re-read your updated pages and compare them with competitors. It's more like building a reputation than switching on a tap. The work we do now is what makes future improvement possible — and we'll show you Search Console so you can see the trend yourself.",
 "Point to impressions trend, not clicks, early on."),
("“Why do we need reels?”",
 "Instagram currently shows short videos to more people who don't follow you yet, and travel is a very visual thing to sell. Reels also give us material we can reuse as ads. They're one part of the mix, not a guarantee of reach.",
 "Avoid claiming reels 'always' get more reach."),
("“Why aren't all 5 ads running?”",
 "We tested all 5, and 2 clearly performed weaker for your audience. With a ₹10,000 budget, it's smarter to put the money behind the ones that are working. Here's the comparison — and the weaker ones still taught us what doesn't work.",
 "Keep a short written note of why each ad was paused."),
("“Why did you stop one ad?”",
 "It was costing more per click and bringing fewer enquiries than the others after a fair test period. Keeping it running would have taken budget from better ads. Here are the numbers side by side.",
 "Show data. Don't stop ads too early without enough spend to judge."),
("“What happens after the first month?”",
 "We'll review everything together: what worked, what didn't, what it cost. Then we'll recommend whether to continue, adjust or pause — and if you continue, what the next month would focus on. No obligation either way.",
 "Don't pre-sell Month 2. Let the data do it."),
]
